# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-08 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ngo',
            fields=[
                ('name', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('phoneNo', models.CharField(max_length=15)),
                ('ngoId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('latitude', models.CharField(max_length=5)),
                ('longitude', models.CharField(max_length=5)),
                ('address', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=10000)),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('cost', models.BigIntegerField()),
                ('status', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('phoneNo', models.CharField(max_length=15)),
                ('fbCred', models.CharField(max_length=100)),
                ('googleCred', models.CharField(max_length=100)),
            ],
        ),
    ]
