# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundsofhope', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngo',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='latitude',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='longitude',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.BigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='fbCred',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='googleCred',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
