# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 00:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundsofhope', '0002_examplemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examplemodel',
            old_name='model_pic',
            new_name='picture',
        ),
    ]
