# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 20:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundsofhope', '0002_auto_20160709_1024'),
        ('fundsofhope', '0003_auto_20160709_0011'),
    ]

    operations = [
    ]
