# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 20:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fundsofhope', '0004_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ngo',
            field=models.ForeignKey(default=datetime.datetime(2016, 7, 9, 20, 24, 24, 438090, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, to='fundsofhope.Ngo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='ngo',
            field=models.ManyToManyField(blank=True, to='fundsofhope.Ngo'),
        ),
        migrations.AddField(
            model_name='user',
            name='projects',
            field=models.ManyToManyField(blank=True, to='fundsofhope.Project'),
        ),
    ]
