# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 19:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundsofhope', '0005_auto_20160709_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ngo',
        ),
    ]
