# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundsofhope', '0006_remove_user_ngo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(default=b'images/default/no-img.jpg', upload_to=b'images/uploads')),
            ],
        ),
        migrations.DeleteModel(
            name='ExampleModel',
        ),
    ]
