# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-21 13:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fundsofhope', '0007_auto_20160712_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fundsofhope.Picture'),
        ),
    ]
