# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-19 10:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import fundsofhope.models


class Migration(migrations.Migration):

    dependencies = [
        ('fundsofhope', '0009_auto_20161021_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='NgoPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ImageField(default=b'images/default/no-img.jpg', upload_to=fundsofhope.models.get_ngo_profile_upload_path)),
                ('head', models.ImageField(default=b'images/default/no-img.jpg', upload_to=fundsofhope.models.get_ngo_head_upload_path)),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fundsofhope.Ngo')),
            ],
        ),
        migrations.AlterField(
            model_name='projectpicture',
            name='picture',
            field=models.ImageField(default=b'images/default/no-img.png', upload_to=fundsofhope.models.get_project_picture_upload_path),
        ),
    ]
