# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-19 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import fundsofhope.models


class Migration(migrations.Migration):

    dependencies = [
        ('fundsofhope', '0010_auto_20161219_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fundsofhope.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(default=b'images/default/no-img.jpg', upload_to=b'images/uploads')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='projects',
        ),
        migrations.AlterField(
            model_name='ngopicture',
            name='head',
            field=models.ImageField(default=b'default/no-img.png', upload_to=fundsofhope.models.get_ngo_head_upload_path),
        ),
        migrations.AlterField(
            model_name='ngopicture',
            name='profile',
            field=models.ImageField(default=b'default/no-img.png', upload_to=fundsofhope.models.get_ngo_profile_upload_path),
        ),
        migrations.AlterField(
            model_name='projectpicture',
            name='picture',
            field=models.ImageField(default=b'default/no-img.png', upload_to=fundsofhope.models.get_project_picture_upload_path),
        ),
        migrations.AddField(
            model_name='donation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fundsofhope.User'),
        ),
    ]
